spring:
  application:
    name: TablEat
    version: 0.0.1-SNAPSHOT
    description: Aplicação desenvolvida para realização de pedidos em um restaurante.

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: a3
    password: "123"

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  main:
    banner-mode: console

logging:
  level:
    org.springframework: info

server:
  port: 8080

info:
  app:
    name: ${spring.application.name}
    version: ${spring.application.version}
    description: ${spring.application.description}
  build:
    timestamp: ${maven.build.timestamp:2025-10-30T00:00:00Z}
  environment:
    profile: ${spring.profiles.active:local}
    java:
      version: ${java.version}
    os:
      name: ${os.name}
      arch: ${os.arch}